version: 2
updates:
- package-ecosystem: nuget
  directory: "/eFormAPI/Plugins/Customers.Pn"
  schedule:
    interval: daily
    time: "04:00"
- package-ecosystem: nuget
  directory: "/eFormAPI/Plugins/Customers.Pn.Test"
  schedule:
    interval: daily
    time: "04:00"