// <auto-generated />
namespace Customers.Pn.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class RelatedEntitiesIds : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RelatedEntitiesIds));
        
        string IMigrationMetadata.Id
        {
            get { return "201809141246301_RelatedEntitiesIds"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
